description: metacognition H200x4 basic, 2 nodes (SDC veRL)

target:
  service: sing
  name: msrresrchbasicvc
  workspace_name: msra-sh-aml-ws

environment:
  image: amlt-sing/acpt-torch2.7.1-py3.10-cuda12.6-ubuntu22.04
  setup:
    - echo "export LC_CTYPE=en_US.UTF-8" >> ~/.profile
    - echo "export CUDA_HOME=/usr/local/cuda-12.6" >> ~/.profile
    - echo "export PATH=/usr/local/cuda-12.6/bin:/opt/conda/envs/ptca/bin:$$PATH" >> ~/.profile
    - echo "export LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64:/opt/conda/envs/ptca/lib:$$LD_LIBRARY_PATH" >> ~/.profile
    - source ~/.profile

code:
  local_dir: $CONFIG_DIR/

storage:
  external:
    storage_account_name: xufluo
    container_name: zhangquanchen
    mount_dir: /mnt/input
    is_output: True

jobs:
  - name: metacognition_h200_a
    sku: 141G4-H200
    sla_tier: basic
    priority: high
    identity: managed
    submit_args:
      max_run_duration_seconds: 1209600
      env:
        _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/c4c534bc-9978-4974-9c87-551f7c5754ef/resourceGroups/msra-sh-aml-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/msra-sh-aml-uai"
    command:
      - nvidia-smi
      - nohup bash -c 'while true; do sleep 3600; done' &
      - sleep infinity

  - name: metacognition_h200_b
    sku: 141G4-H200
    sla_tier: basic
    priority: high
    identity: managed
    submit_args:
      max_run_duration_seconds: 1209600
      env:
        _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/c4c534bc-9978-4974-9c87-551f7c5754ef/resourceGroups/msra-sh-aml-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/msra-sh-aml-uai"
    command:
      - nvidia-smi
      - nohup bash -c 'while true; do sleep 3600; done' &
      - sleep infinity
