"""Agent Lightning training script for metacognitive math reasoning.

Uses Agent Lightning + verl for GRPO training with:
- <|meta|> step-level credit assignment
- R_correct (=2.0), R_calib, R_penalty rewards
- 4-GPU FSDP training via verl
- Gnosis probe for p̂ at each <|meta|> position

Usage:
    conda activate verl
    python -m src.training.al_train \
        --train-file rollouts/rollouts_final.parquet \
        --model checkpoints/meta_sft
"""
import argparse
import os
import re
import sys
from typing import Any, Dict, TypedDict, cast

sys.path.insert(0, os.getcwd())

from datasets import Dataset as HFDataset

import agentlightning as agl

from src.metacot.prompt import META_START, META_END, parse_meta_blocks
from src.training.rewards import compute_r_correct, compute_r_calib, compute_r_penalty
from src.rollout.vllm_rollout import check_correctness


class MathTask(TypedDict):
    question: str
    gold_answer: str
    problem_id: str
    category: str


SYSTEM_PROMPT = (
    "You are a math problem solver with metacognitive awareness. "
    "Use <|meta|> and <|/meta|> tags to reflect on your reasoning. "
    "Before solving, assess difficulty. During solving, verify uncertain steps. "
    "After solving, reflect on what you learned. "
    "Put your final answer in \\boxed{}."
)


def metacot_reward_fn(response_text: str, gold_answer: str) -> Dict[str, float]:
    """Compute metacognitive rewards from agent response."""
    # Parse meta blocks
    parsed = parse_meta_blocks(response_text)
    num_meta = parsed["num_blocks"]
    confidences = parsed["confidences"]

    # R_correct
    is_correct = check_correctness(response_text, gold_answer)
    r_correct = compute_r_correct(is_correct)

    # R_penalty
    r_penalty = compute_r_penalty(num_meta)

    # R_calib (use model's stated confidence — probe will be added later)
    # For now, reward having confidence at all
    r_calib = 0.0
    if confidences:
        # Reward if confidence correlates with correctness
        avg_conf = sum(confidences) / len(confidences)
        if is_correct and avg_conf > 0.5:
            r_calib = avg_conf  # confident and correct
        elif not is_correct and avg_conf < 0.5:
            r_calib = 1.0 - avg_conf  # uncertain and wrong (good self-awareness)
        else:
            r_calib = 0.1  # partial credit

    total = r_correct + r_calib + r_penalty

    return {
        "reward": total,
        "r_correct": r_correct,
        "r_calib": r_calib,
        "r_penalty": r_penalty,
        "num_meta": float(num_meta),
        "is_correct": float(is_correct),
    }


@agl.LitAgent()
async def metacot_agent(task: MathTask) -> str:
    """Math agent with metacognitive reasoning."""
    question = task["question"]
    gold_answer = task["gold_answer"]

    # The agent's response will be generated by the LLM (via vLLM server)
    # Agent Lightning handles the LLM call through LLM Proxy
    response = await agl.emit_message(
        role="user",
        content=f"{SYSTEM_PROMPT}\n\nProblem: {question}",
    )

    # Get the model's response
    response_text = response if isinstance(response, str) else str(response)

    # Compute and emit rewards
    rewards = metacot_reward_fn(response_text, gold_answer)

    # Emit multi-dimensional reward
    agl.emit_reward({
        "task_reward": rewards["reward"],
        "r_correct": rewards["r_correct"],
        "r_calib": rewards["r_calib"],
        "r_penalty": rewards["r_penalty"],
    })

    # Emit annotations for tracking
    agl.emit_annotation("num_meta_blocks", rewards["num_meta"])
    agl.emit_annotation("is_correct", rewards["is_correct"])

    return response_text


def verl_config(model_path: str, n_gpus: int = 4) -> Dict[str, Any]:
    """VERL config for metacognitive GRPO training."""
    return {
        "algorithm": {
            "adv_estimator": "grpo",
            "use_kl_in_reward": False,
        },
        "data": {
            "train_batch_size": 32,
            "max_prompt_length": 2048,
            "max_response_length": 2048,
        },
        "actor_rollout_ref": {
            "rollout": {
                "tensor_model_parallel_size": 1,
                "n": 4,  # group_size for GRPO
                "log_prob_micro_batch_size_per_gpu": 4,
                "name": "vllm",
                "gpu_memory_utilization": 0.7,
            },
            "actor": {
                "ppo_mini_batch_size": 16,
                "ppo_micro_batch_size_per_gpu": 2,
                "optim": {"lr": 5e-6},
                "use_kl_loss": False,
                "kl_loss_coef": 0.0,
                "entropy_coeff": 0,
                "clip_ratio_low": 0.2,
                "clip_ratio_high": 0.3,
                "fsdp_config": {
                    "param_offload": True,
                    "optimizer_offload": True,
                },
            },
            "ref": {
                "log_prob_micro_batch_size_per_gpu": 4,
                "fsdp_config": {"param_offload": True},
            },
            "model": {
                "path": model_path,
                "use_remove_padding": True,
                "enable_gradient_checkpointing": True,
            },
        },
        "trainer": {
            "n_gpus_per_node": n_gpus,
            "val_before_train": True,
            "critic_warmup": 0,
            "logger": ["console", "wandb"],
            "project_name": "metacot-math",
            "experiment_name": "metacot-grpo-agentlightning",
            "nnodes": 1,
            "save_freq": 200,
            "test_freq": 100,
            "total_epochs": 3,
            "total_training_steps": 1000,
        },
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--train-file", required=True)
    parser.add_argument("--val-file", default=None)
    parser.add_argument("--model", default="checkpoints/meta_sft")
    parser.add_argument("--n-gpus", type=int, default=4)
    parser.add_argument("--llm-proxy", action="store_true", default=True)
    args = parser.parse_args()

    # Load dataset
    import pandas as pd
    df = pd.read_parquet(args.train_file)
    problems = df.drop_duplicates("problem_id")
    train_data = [
        MathTask(
            question=row["question"],
            gold_answer=row["gold_answer"],
            problem_id=row["problem_id"],
            category=row["category"],
        )
        for _, row in problems.iterrows()
    ]

    val_data = train_data[:100] if args.val_file is None else None

    print(f"Train: {len(train_data)} problems", flush=True)

    config = verl_config(args.model, n_gpus=args.n_gpus)
    algorithm = agl.VERL(config)

    tracer = agl.OtelTracer()
    adapter = agl.LlmProxyTraceToTriplet()

    trainer = agl.Trainer(
        algorithm=algorithm,
        n_runners=2,
        tracer=tracer,
        adapter=adapter,
        runner=metacot_agent,
        initial_resources={
            "train_dataset": train_data,
            "val_dataset": val_data,
        },
    )

    trainer.fit()


if __name__ == "__main__":
    main()
